Art-Gallery/Models/Agent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Art_Gallery.Models
{
    public class Agent
    {
        public int AgentId { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public bool Active { get; set; }
    }
}

Art-Gallery/ViewModels/AgentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Art_Gallery.ViewModels
{
    public class AgentViewModel
    {
        public int AgentId { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public bool Active { get; set; }
        public string PieceSold { get; set; }
        public double Sales { get; set; }
        public double Profit { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
    }
}

Art-Gallery/Controllers/OwnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.SqlClient;
using System.Web;
using System.Web.Mvc;
using Art_Gallery.ViewModels;
using Art_Gallery.Models;

namespace Art_Gallery.Controllers
{
    public class OwnerController : Controller
    {

        // **********************
        // ARTWORK INFORMATION -- CRUD
        // **********************

        public ActionResult Index()
        {
            DataStoreContext db = new DataStoreContext();
            var pieceList = (from aw in db.ArtWork
                            join ip in db.IndividualPiece
                            on aw.ArtWorkId equals ip.ArtWorkId
                            select new PieceViewModel
                            {
                                IndividualPieceId = ip.IndividualPieceId,
                                Title = aw.Title,
                                Cost = ip.Cost,
                                AskingPrice = ip.Price,
                                Sold = ip.Sold
                            }).ToList();

            InventoryViewModel inventory = new InventoryViewModel
            {
                Pieces = pieceList
            };

            return View(inventory);
        }

        // CREATE - GET
        [HttpGet]
        public ActionResult CreatePiece()
        {
            return View();
        }


        // CREATE - POST
        [HttpPost]
        public ActionResult CreatePiece(PieceViewModel pieces)
        {
            using (DataStoreContext db = new DataStoreContext())
            {
                if (ModelState.IsValid)
                {
                    var matchingArtWork = db.ArtWork.First(a => a.Title == pieces.Title).ArtWorkId;

                    if (matchingArtWork > 0)
                    {
                        IndividualPiece piece = new IndividualPiece
                        {
                            ArtWorkId = matchingArtWork,
                            Image = pieces.Image,
                            Price = pieces.AskingPrice,
                            Cost = pieces.Cost,
                            Sold = pieces.Sold,
                            EditionNumber = pieces.EditionNumber,
                            Location = pieces.Location,
                            InvoiceId = null
                        };
                        db.IndividualPiece.Add(piece);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else {
                        ViewBag.Title = "Our system currently only supports adding new prints of existing art.";
                    }
                }

                return View(pieces);
            }
        }

        // EDIT - GET
        [HttpGet]
        public ActionResult EditPiece(int IndividualPieceId)
        {
            using (DataStoreContext db = new DataStoreContext())
            {
                var pieces = (from aw in db.ArtWork
                              join ip in db.IndividualPiece
                              on aw.ArtWorkId equals ip.ArtWorkId
                              where ip.IndividualPieceId == IndividualPieceId
                              select new PieceViewModel
                              {
                                  IndividualPieceId = ip.IndividualPieceId,
                                  Title = aw.Title,
                                  Cost = ip.Cost,
                                  AskingPrice = ip.Price,
                                  Sold = ip.Sold
                              }).ToList();


                PieceViewModel pieceForEdit = new PieceViewModel
                {
                    Title = pieces.Select(p => p.Title).FirstOrDefault(),
                    Cost = pieces.Select(p => p.Cost).FirstOrDefault(),
                    AskingPrice = pieces.Select(p => p.AskingPrice).FirstOrDefault(),
                    Sold = pieces.Select(p => p.Sold).FirstOrDefault()
                };


                return View(pieceForEdit);
            }
        }

        // EDIT - POST
        [HttpPost]
        public ActionResult EditPiece(PieceViewModel pieces)
        {
            using (DataStoreContext db = new DataStoreContext())
            {
                var piece = db.IndividualPiece.Find(pieces.IndividualPieceId);

                if (ModelState.IsValid)
                {
                    piece.Cost = pieces.Cost;
                    piece.Price = pieces.AskingPrice;
                    piece.Sold = pieces.Sold;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(pieces);
            }
        }

        // DELETE
        public ActionResult DeletePiece(int IndividualPieceId)
        {
            if (IndividualPieceId != 0)
            {
                using (DataStoreContext db = new DataStoreContext())
                {
                    IndividualPiece piece = db.IndividualPiece.Find(IndividualPieceId);

                    db.IndividualPiece.Remove(piece);
                    db.SaveChanges();

                }
            }
            else
            {
                ViewBag.Title = "There was a problem";
            }
            return RedirectToAction("Index");
        }


        // **********************
        // VIEW SALES INFORMATION
        // **********************

        public ActionResult Sales()
        {
            DataStoreContext db = new DataStoreContext();
            var soldPieces = (from ip in db.IndividualPiece
                              where ip.Sold == true
                              join aw in db.ArtWork
                              on ip.ArtWorkId equals aw.ArtWorkId
                              select new PieceViewModel
                              {
                                  Title = aw.Title,
                                  Cost = ip.Cost,
                                  AskingPrice = ip.Price,
                                  Sold = ip.Sold
                              }).ToList();
            InventoryViewModel inventory = new InventoryViewModel
            {
                Pieces = soldPieces,
                TotalProfit = 0,
                TotalSales = 0
            };

            foreach (var piece in inventory.Pieces)
            {
                inventory.TotalSales += piece.AskingPrice;
                inventory.TotalProfit += (piece.AskingPrice - piece.Cost);
            }
            return View(inventory);
        }


        // **********************
        // AGENT INFORMATION -- view, create, edit
        // **********************

        public ActionResult Agents()
        {
            DataStoreContext db = new DataStoreContext();
            var agents = (from a in db.Agent
                          join i in db.Invoice
                          on a.AgentId equals i.AgentId
                          orderby a.Name
                          select new AgentViewModel
                          {
                              AgentId = a.AgentId,
                              Name = a.Name,
                              Location = a.Location,
                              Active = a.Active,
                              PieceSold = i.PieceSold
                          }).ToList();



            foreach (var agent in agents)
            {
                string[] pieces = agent.PieceSold.Split(',');
                double totalSales = 0;
                double totalProfit = 0;
                foreach (var piece in pieces)
                {
                    var individualSale = (
                                 from ip in db.IndividualPiece
                                 where ip.Sold == true
                                 join aw in db.ArtWork
                                 on ip.ArtWorkId equals aw.ArtWorkId
                                 where aw.Title == piece
                                 select new PriceViewModel
                                 {
                                     Price = ip.Price,
                                     Cost = ip.Cost
                                 }).ToList();
                    if (individualSale.Count > 0)
                    {
                        totalSales += individualSale[0].Price;
                        double profit = individualSale[0].Price - individualSale[0].Cost;
                        totalProfit += profit;
                    }
                }
                agent.Sales = Math.Round(totalSales, 2);
                agent.Profit = Math.Round(totalProfit, 2);
            }

            // brute force solution for displaying unique agents & profit/sales totals
            for (int i = 0; i < agents.Count; i++)
            {
                if ((i + 1 != agents.Count) && agents[i].Name == agents[i + 1].Name)
                {
                    if (agents[i + 2].Name == agents[i + 1].Name)
                    {
                        agents[i + 1].PieceSold += "," + agents[i + 2].PieceSold;
                        agents[i + 1].Sales += agents[i + 2].Sales;
                        agents[i + 1].Profit += agents[i + 2].Profit;
                        agents.Remove(agents[i + 2]);
                    } 
                    agents[i + 1].PieceSold += ", " + agents[i].PieceSold;
                    agents[i + 1].Sales += agents[i].Sales;
                    agents[i + 1].Profit += agents[i].Profit;
                    agents.Remove(agents[i]);
                }
            }


            // need to add new agents to this list
            // new agent = not represented on above agents list, 
            // will not have an invoice

            var potentialNewAgents = db.Agent.ToList();
            foreach (var potentialNewAgent in potentialNewAgents)
            {
                if (potentialNewAgent.AgentId > 7)
                {

Art-Gallery/Views/Owner/Agents.cshtml
@model Art_Gallery.ViewModels.AgentSalesViewModel
@{
    ViewBag.Title = "Agents";
}

<h2>Agents</h2>

@Html.ActionLink("Add an Agent", "CreateAgent")

<table>
    <tr>
        <th>@Html.DisplayNameFor(model => model.Name)</th>
        <th>@Html.DisplayNameFor(model => model.Location)</th>
        <th>@Html.DisplayNameFor(model => model.PiecesSold)</th>
        <th>@Html.DisplayNameFor(model => model.TotalSales)</th>
        <th>@Html.DisplayNameFor(model => model.TotalProfit)</th>
        <th>@Html.DisplayNameFor(model => model.Active)?</th>
    </tr>
    @foreach (var agent in Model.Agents)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => agent.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => agent.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => agent.PieceSold)
            </td>
            <td>
                $@Html.DisplayFor(modelItem => agent.Sales)
            </td>
            <td>
                $@Html.DisplayFor(modelItem => agent.Profit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => agent.Active)
            </td>
            <td>
                @Html.ActionLink("Edit", "/EditAgent", new { agentId = agent.AgentId })
            </td>
        </tr>
    }
</table>

Art-Gallery/Views/Owner/CreateAgent.cshtml
@model Art_Gallery.ViewModels.AgentViewModel
@{
    ViewBag.Title = "CreateAgent";
}

<h2>Create an Agent</h2>

@using (Html.BeginForm())
{
    @Html.Label("Name")
    @Html.EditorFor(model => model.Name)

    @Html.Label("Location")
    @Html.EditorFor(model => model.Location)

    @Html.Label("Address")
    @Html.EditorFor(model => model.Address)

    @Html.Label("Phone Number")
    @Html.EditorFor(model => model.PhoneNumber)

    @Html.Label("Active")
    @Html.EditorFor(model => model.Active)

    <input type="submit" value="Create" />
}

@Html.ActionLink("Back to homepage", "Agents")

Art-Gallery/Views/Owner/CreateArtWork.cshtml
@model Art_Gallery.ViewModels.ArtWorkViewModel
@*@{
    ViewBag.Title = "CreateArtWork";
}*@

<h2>Add New ArtWork</h2>


@*<form asp-controller="Owner" asp-action="Create">
    @Html.DropDownList("artistString", "All Artists")
    <input type="submit" value="Select" />
</form>*@



@using (Html.BeginForm())
{
    <p>
        @Html.Label("Artist")
        @Html.EditorFor(model => model.Artist)
    </p>
    <p>
        @Html.Label("Title")
        @Html.EditorFor(model => model.Title)
    </p>
    <p>
        @Html.Label("Year Original Created")
        @Html.EditorFor(model => model.YearOriginalCreated)
    </p>
    <p>
        @Html.Label("Medium")
        @Html.EditorFor(model => model.Medium)
    </p>
    <p>
        @Html.Label("Dimensions")
        @Html.EditorFor(model => model.Dimensions)
    </p>
    <p>
        @Html.Label("Number Made")
        @Html.EditorFor(model => model.NumberMade)
    </p>
    <p>
        @Html.Label("Number In Inventory")
        @Html.EditorFor(model => model.NumberInInventory)
    </p>
    <p>
        @Html.Label("Number Sold")
        @Html.EditorFor(model => model.NumberSold)
    </p>
    <p>
        <input type="submit" value="Add" />
    </p>
}

@Html.ActionLink("Back to homepage", "Index")

Art-Gallery/Views/Owner/CreatePiece.cshtml
@model Art_Gallery.ViewModels.PieceViewModel
@{
    ViewBag.Title = "Create Piece";
}

<h2>Create a Piece</h2>

@using (Html.BeginForm())
{
    @Html.Label("Title")
    @Html.EditorFor(model => model.Title)

    @Html.Label("Image")
    @Html.EditorFor(model => model.Image)

    @Html.Label("Cost")
    @Html.EditorFor(model => model.Cost)

    @Html.Label("Price")
    @Html.EditorFor(model => model.AskingPrice)

    @Html.Label("Sold")
    @Html.EditorFor(model => model.Sold)

    @Html.Label("Edition Number")
    @Html.EditorFor(model => model.EditionNumber)

    @Html.Label("Location")
    @Html.EditorFor(model => model.Location)

    <input type="submit" value="Create" />
}

@Html.ActionLink("Back to homepage", "Index")

Art-Gallery/Views/Owner/EditAgent.cshtml
@model Art_Gallery.ViewModels.AgentViewModel
@{
    ViewBag.Title = "Edit An Agent";
}

<h2>Edit</h2>



@using (Html.BeginForm())
{
    @Html.Label("Name")
    @Html.EditorFor(model => model.Name)
    @Html.Label("Location")
    @Html.EditorFor(model => model.Location)
    @Html.Label("Active")
    @Html.EditorFor(model => model.Active)
    <input type="submit" value="Edit" />
}

Art-Gallery/Views/Owner/EditPiece.cshtml
@model Art_Gallery.ViewModels.PieceViewModel
@{
    ViewBag.Title = "Edit A Piece";
}

<h2>Edit A Piece</h2>



@using (Html.BeginForm())
{
    <p>
        @Html.Label("Title")
        @Html.DisplayFor(model => model.Title)
    </p>
    <p>
        @Html.Label("Cost")
        @Html.EditorFor(model => model.Cost)
    </p>
    <p>
        @Html.Label("Asking Price")
        @Html.EditorFor(model => model.AskingPrice)
    </p>
    <p>
        @Html.Label("Sold")
        @Html.EditorFor(model => model.Sold)
    </p>
    <p>
        <input type="submit" value="Edit" />
    </p>
}

Art-Gallery/Views/Owner/Index.cshtml
@model Art_Gallery.ViewModels.InventoryViewModel
@{
    ViewBag.Title = "Your Inventory";
}

<h2>Your Inventory</h2>

@Html.ActionLink("Add a Piece", "CreatePiece")
@Html.ActionLink("Add ArtWork", "CreateArtWork") @*link to add new ArtWork*@

<table>
    <tr>
        <th>@Html.DisplayNameFor(model => model.Title)</th>
        <th>@Html.DisplayNameFor(model => model.Cost)</th>
        <th>@Html.DisplayNameFor(model => model.AskingPrice)</th>
        <th>@Html.DisplayNameFor(model => model.Sold)</th>
    </tr>
    @foreach (var piece in Model.Pieces)
    {
        <tr>
            <td>
                "@Html.DisplayFor(modelItem => piece.Title)"
            </td>
            <td>
                $@Html.DisplayFor(modelItem => piece.Cost)
            </td>
            <td>
                $@Html.DisplayFor(modelItem => piece.AskingPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => piece.Sold)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditPiece", new { IndividualPieceId = piece.IndividualPieceId })
            </td>
            <td>
                @Html.ActionLink("Delete", "DeletePiece", new { IndividualPieceId = piece.IndividualPieceId })
            </td>
        </tr>
    }
</table>

Art-Gallery/Views/Owner/Sales.cshtml
@model Art_Gallery.ViewModels.InventoryViewModel
@{
    ViewBag.Title = "Sales";
}

<h2>Sales</h2>

<table>
    <tr>
        <th>@Html.DisplayNameFor(model => model.Title)</th>
        <th>@Html.DisplayNameFor(model => model.Cost)</th>
        <th>@Html.DisplayNameFor(model => model.AskingPrice)</th>
        <th>Profit</th>
    </tr>
    @foreach (var piece in Model.Pieces)
    {
        <tr>
            <td>
                "@Html.DisplayFor(modelItem => piece.Title)"
            </td>
            <td>
                $@Html.DisplayFor(modelItem => piece.Cost)
            </td>
            <td>
                $@Html.DisplayFor(modelItem => piece.AskingPrice)
            </td>
            <td>
                $@(piece.AskingPrice - piece.Cost)
            </td>
        </tr>
    }
</table>

<div>
    <p>Total Sales: $@Model.TotalSales</p>
    <p>Total Profit: $@Model.TotalProfit</p>
</div>